answer_index:
    path:     /
    defaults: { _controller: "InterviewBundle:Answer:index" }
    methods:  GET


answer_get:
    path:     /getAnswers
    defaults: { _controller: "InterviewBundle:Answer:getAnswers" }
    methods:  GET
answer_interview:
    path:     /interview
    defaults: { _controller: "InterviewBundle:Answer:interview" }
    methods:  GET


answer_show:
    path:     /{id}/show
    defaults: { _controller: "InterviewBundle:Answer:show" }
    methods:  GET

answer_new:
    path:     /new
    defaults: { _controller: "InterviewBundle:Answer:new" }
    methods:  [GET, POST]

answer_edit:
    path:     /{id}/edit
    defaults: { _controller: "InterviewBundle:Answer:edit" }
    methods:  [GET, POST]

answer_delete:
    path:     /{id}/delete
    defaults: { _controller: "InterviewBundle:Answer:delete" }
    methods:  DELETE
