question_index:
    path:     /
    defaults: { _controller: "InterviewBundle:Question:index" }
    methods:  GET

question_all:
    path:     /all
    defaults: { _controller: "InterviewBundle:Question:getQuestion" }
    methods:  GET


question_show:
    path:     /{id}/show
    defaults: { _controller: "InterviewBundle:Question:show" }
    methods:  GET

question_new:
    path:     /new
    defaults: { _controller: "InterviewBundle:Question:new" }
    methods:  [GET, POST]

question_edit:
    path:     /{id}/edit
    defaults: { _controller: "InterviewBundle:Question:edit" }
    methods:  [GET, POST]

question_delete:
    path:     /{id}/delete
    defaults: { _controller: "InterviewBundle:Question:delete" }
    methods:  DELETE
