offre:
    resource: "@OffreBundle/Resources/config/routing.yml"
    prefix:   /

auth:
    resource: "@AuthBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

profile:
    path:  /profile
    defaults: { _controller: AuthBundle:Default:profile }

index:
    path:  /
    defaults: { _controller: AuthBundle:Default:index }

browse_jobs:
    path:  /job-list/
    defaults: { _controller: OffreBundle:Offre:browse_jobs }

show_detail:
    path:  /job-detail/{id}
    defaults: { _controller: OffreBundle:Offre:show_detail }
    
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


question:
    prefix:     /question
    resource: "@InterviewBundle/Resources/config/routing/question.yml"


answer:
    prefix:     /answer
    resource: "@InterviewBundle/Resources/config/routing/answer.yml"


interview:
    prefix:     /interview
    resource: "@InterviewBundle/Resources/config/routing/interview.yml"

register13:
    path:     /detect/{projectId}/{text}/{sessionId}/{languageCode}
    defaults: { _controller: AppBundle:Default:detect }

question_all:
    path:     /api/getq
    defaults: { _controller: "InterviewBundle:Question:getQuestion" }
    methods:  GET

send_answers:
    path:     /api/send
    defaults: { _controller: "InterviewBundle:Answer:sendAnswers" }
    methods:  POST